add TDatabaseObjectToggle trait
WoltLab/WCF pull request #2763
Opened 2018-10-28 14:18 UTC by mutec

see #2728 
Closes #2728

2018-10-29 17:11 UTC, ghost requested changes

2018-10-29 17:11 UTC, Gravatronics commented on wcfsetup/install/files/lib/data/TDatabaseObjectToggle.class.php
> + * Provides a method for toggling the "isDisabled" status of database objects.
```suggestion
 * Default implementation of the `IToggleAction` interface.
```

2018-10-29 17:12 UTC, Gravatronics commented
Would you mind changing the existing classes in Core implementing `IToggleAction` this way to use this trait instead?

2018-11-02 16:59 UTC, ghost approved these changes

2018-11-07 10:49 UTC, merged

2018-11-07 10:49 UTC, dtdesign commented
Thanks!