Add button form field
WoltLab/WCF pull request #3694
Opened 2020-11-04 15:50 UTC by Gravatronics

Close #3693

2020-11-06 15:43 UTC, TimWolla approved these changes

2020-11-06 16:22 UTC, dtdesign requested changes

2020-11-06 16:22 UTC, dtdesign commented on wcfsetup/install/files/js/WoltLabSuite/Core/Form/Builder/Dialog.js
> +                        }
```suggestion
                        button.dataset.isClicked = (button === submit) ? "1" : "0"
```

2020-11-06 16:22 UTC, dtdesign commented on wcfsetup/install/files/ts/WoltLabSuite/Core/Form/Builder/Dialog.js
> +						}
```suggestion
						button.dataset.isClicked = (button === submit) ? "1" : "0";
```

2020-11-07 10:25 UTC, dtdesign approved these changes

2020-11-07 11:53 UTC, merged