Add update_com.woltlab.wcf_5.4_migrate_multifactor.php
WoltLab/WCF pull request #3766
Opened 2020-11-27 10:04 UTC by TimWolla

2020-11-27 16:13 UTC, TimWolla commented on wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_migrate_multifactor.php
> +		$parts = explode('-', $row['backupCode'], 2);
```suggestion
		$parts = \explode('-', $row['backupCode'], 2);
```

2020-11-27 16:13 UTC, TimWolla commented on wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_migrate_multifactor.php
> +		$code = @base64_decode($parts[1]);
```suggestion
		$code = @\base64_decode($parts[1]);
```

2020-11-28 15:19 UTC, dtdesign requested changes

2020-11-28 15:19 UTC, dtdesign commented on wcfsetup/install/files/acp/update_com.woltlab.wcf_5.4_migrate_multifactor.php
> +	$totpMethod->objectTypeID
```suggestion
	$totpMethod->objectTypeID,
```

2020-11-30 11:26 UTC, merged