Log sitemap files for packages to delete them on uninstallation
WoltLab/WCF pull request #4006
Opened 2021-02-20 14:47 UTC by joshuaruesweg

2021-02-20 18:51 UTC, dtdesign requested changes
LGTM

2021-02-20 18:51 UTC, dtdesign commented on wcfsetup/install/files/lib/system/worker/SitemapRebuildWorker.class.php
> +                $this->finishSitemap($this->sitemapObjects[$this->workerData['sitemap']]->objectType . '_' . $this->workerData['sitemapLoopCount'] . '.xml', $this->sitemapObjects[$this->workerData['s
Please use temporary variables, this deep access is barely readable.

2021-02-20 18:51 UTC, dtdesign commented on wcfsetup/install/files/lib/system/worker/SitemapRebuildWorker.class.php
> +                    $this->finishSitemap($this->sitemapObjects[$this->workerData['sitemap']]->objectType . '.xml', $this->sitemapObjects[$this->workerData['sitemap']]->packageID);
Same as for line 210, use temporary variables please.

2021-02-21 11:18 UTC, joshuaruesweg commented
Check failed, because `master` is failing atm.

2021-02-21 13:46 UTC, dtdesign commented
> Check failed, because `master` is failing atm.

Already resolved.

2021-02-22 09:40 UTC, TimWolla approved these changes

2021-02-22 10:24 UTC, merged