Fix requesting multiple times the UserStorage tables if no cache exists
WoltLab/WCF pull request #4127
Opened 2021-04-16 10:46 UTC by joshuaruesweg

2021-04-16 11:37 UTC, TimWolla approved these changes

2021-04-16 11:38 UTC, TimWolla requested changes
Ah, one thing: Please remove the check in the while-loop. It is no longer required.

2021-04-19 08:10 UTC, TimWolla approved these changes

2021-04-19 11:44 UTC, dtdesign approved these changes

2021-04-19 11:45 UTC, merged