Add support for version upgrades
WoltLab/WCF pull request #4160
Opened 2021-04-28 11:44 UTC by TimWolla

Resolves #4141

2021-04-28 13:27 UTC, dtdesign approved these changes
LGTM.

Can we get a check for PHP/MySQl requirements built into the activation process for the upgrade?

2021-04-28 13:36 UTC, TimWolla commented
> Can we get a check for PHP/MySQl requirements built into the activation process for the upgrade?

Sure. That's why this still is a draft with a general PoC :smiley:

2021-04-28 14:39 UTC, dtdesign requested changes
LGTM

2021-04-28 14:39 UTC, dtdesign commented on wcfsetup/install/lang/de.xml
> +		<item name="wcf.acp.package.availableUpgradeVersion"><![CDATA[Ein WoltLab Suite-Upgrade zur Verfügung. <a href="{link controller='PackageEnableUpgradeOverride' application='wcf'}{/link}">System prü
```suggestion
		<item name="wcf.acp.package.availableUpgradeVersion"><![CDATA[Ein WoltLab Suite-Upgrade steht zur Verfügung. <a href="{link controller='PackageEnableUpgradeOverride' application='wcf'}{/link}">System prüfen und Upgrade freigeben</a>.]]></item>
```

2021-04-28 14:39 UTC, dtdesign commented on wcfsetup/install/lang/de.xml
> +		<item name="wcf.acp.package.upgradeOverrideEnabled"><![CDATA[Die Installation eines WoltLab Suite-Upgrades wurde freigegeben. Die Durchführung von Updates wird {if LANGUAGE_USE_INFORMAL_VARIANT}dei
```suggestion
		<item name="wcf.acp.package.upgradeOverrideEnabled"><![CDATA[Die Installation eines WoltLab Suite-Upgrades wurde freigegeben. Die Durchführung von Updates wird {if LANGUAGE_USE_INFORMAL_VARIANT}deine{else}Ihre{/if} Community auf eine neue Version von WoltLab Suite aktualisieren. <a href="{link controller='PackageEnableUpgradeOverride' application='wcf'}{/link}">Freigabe zurückziehen</a>.]]></item>
```

2021-06-25 13:22 UTC, jens1o commented on wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php
> +			'requested-woltlab-suite-version',
```suggestion
			'x-requested-woltlab-suite-version',
```
?

2021-06-25 13:32 UTC, TimWolla commented on wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php
> +			'requested-woltlab-suite-version',
No, RFC 6648.

2021-06-28 10:08 UTC, TimWolla commented on wcfsetup/install/files/lib/acp/page/PackageListPage.class.php
> +			'availableUpgradeVersion' => WCF::AVAILABLE_UPGRADE_VERSION,
```suggestion
			'availableUpgradeVersion' => $availableUpgradeVersion,
```

2021-06-28 10:08 UTC, TimWolla commented on wcfsetup/install/files/acp/templates/packageUpdateServerList.tpl
> +			<p class="info">{lang}wcf.acp.package.availableUpgradeVersion{/lang}</p>
```suggestion
			<p class="info">{lang version=$availableUpgradeVersion}wcf.acp.package.availableUpgradeVersion{/lang}</p>
```

2021-06-28 10:08 UTC, TimWolla commented on wcfsetup/install/files/acp/templates/packageUpdateServerList.tpl
> +			<p class="info">{lang}wcf.acp.package.upgradeOverrideEnabled{/lang}</p>
```suggestion
			<p class="info">{lang version=$availableUpgradeVersion}wcf.acp.package.upgradeOverrideEnabled{/lang}</p>
```

2021-06-28 10:08 UTC, TimWolla commented on wcfsetup/install/files/lib/acp/page/PackageUpdateServerListPage.class.php
> +			'upgradeOverrideEnabled' => PackageUpdateServer::isUpgradeOverrideEnabled(),
Should this look like `PackageListPage`?

2021-06-28 14:44 UTC, merged