Overhaul of the user object watch button
WoltLab/WCF pull request #4962
Opened 2022-08-15 14:22 UTC by BurntimeX

This PR has two goals:
- Dropping the old subscribe dialog and using the UI as the 5.5 version of the forum instead
- Rewriting of the old jQuery-Code into Typescript

2022-08-15 16:17 UTC, dtdesign requested changes

2022-08-15 16:17 UTC, dtdesign commented on com.woltlab.wcf/templates/__userObjectWatchButton.tpl
> +		require([ 'WoltLabSuite/Core/Ui/User/ObjectWatch', 'Language'], function (ObjectWatch, Language) {
```suggestion
		require(['WoltLabSuite/Core/Ui/User/ObjectWatch', 'WoltLabSuite/Core/Language'], (ObjectWatch, Language) => {
```

2022-08-15 16:17 UTC, dtdesign commented on com.woltlab.wcf/templates/__userObjectWatchButton.tpl
> +                'wcf.user.objectWatch.button.subscribed': '{jslang}wcf.user.objectWatch.button.subscribed{/jslang}',
```suggestion
				'wcf.user.objectWatch.button.subscribed': '{jslang}wcf.user.objectWatch.button.subscribed{/jslang}',
```

2022-08-15 16:17 UTC, dtdesign commented on com.woltlab.wcf/templates/categoryArticleList.tpl
> +	{include file='__userObjectWatchButton' isSubscribed=$category->isSubscribed() objectType="com.woltlab.wcf.article.category" objectID=$category->categoryID}
```suggestion
	{include file='__userObjectWatchButton' isSubscribed=$category->isSubscribed() objectType='com.woltlab.wcf.article.category' objectID=$category->categoryID}
```

2022-08-15 16:17 UTC, dtdesign commented on ts/WoltLabSuite/Core/Ui/User/ObjectWatch.ts
> +      element.querySelector(`.userObjectWatchSelect[data-subscribe="${subscribe}"]`)?.classList.add("active");
This can be merged with the `forEach` block above, you are iterating over all elements anyway instead of just the `.active` elements.

2022-08-15 18:46 UTC, dtdesign approved these changes

2022-08-16 09:59 UTC, merged

2023-01-02 14:33 UTC, mutec commented
Do you plan to provide a "small" discrete solution too?
Using the new template/generic button is really ugly in lists without much text or information:
![image](https://user-images.githubusercontent.com/1749344/210245192-64ed3d77-fb94-4582-ae6c-23e832fa9296.png)

2023-01-02 15:37 UTC, BurntimeX commented
There are no plans for this from our side.