Add logic to sync a user's TZ with their browser timezone
WoltLab/WCF pull request #5054
Opened 2022-10-19 08:12 UTC by TimWolla

2022-10-19 11:55 UTC, TimWolla commented on ts/WoltLabSuite/Core/Controller/User/Profile/TimezoneSync.ts
> + * @package WoltLabSuite\Core\Data\User
fix

2022-10-19 11:55 UTC, TimWolla commented on wcfsetup/install/files/lib/action/UserTimezoneSyncAction.class.php
> + * @package WoltLabSuite\Core\Data\User
fix

2022-10-19 11:59 UTC, dtdesign requested changes

2022-10-19 11:59 UTC, dtdesign commented on ts/WoltLabSuite/Core/Controller/User/Profile/TimezoneSync.ts
> + * @package WoltLabSuite\Core\Data\User
```suggestion
 * @package WoltLabSuite\Core\Data\User
 * @since 6.0
```

2022-10-19 11:59 UTC, dtdesign commented on ts/WoltLabSuite/Core/Controller/User/Profile/TimezoneSync.ts
> +    await fetch(`${window.WSC_API_URL}index.php?user-timezone-sync/`, {
Fetch can fail loud. This should be enclosed in `try … catch`, because we do not care about failed requests (outside of the debug mode).

2022-10-19 11:59 UTC, dtdesign commented on wcfsetup/install/files/lib/action/UserTimezoneSyncAction.class.php
> +            }
This smells like a good opportunity for a ready-made helper method in `$form`.

2022-10-20 13:46 UTC, TimWolla commented on wcfsetup/install/files/lib/action/UserTimezoneSyncAction.class.php
> +        }
With #5059 this (c|sh)ould be transformed to:

```suggestion
        if ($request->getAttribute(Xsrf::HAS_VALID_HEADER_ATTRIBUTE) !== true) {
            throw new InvalidSecurityTokenException();
        }
```

2023-02-16 15:17 UTC, closed without merging