Return Types for `ITitledObject::getLink()` and `ILinkableObject::getLink()`
WoltLab/WCF pull request #5157
Opened 2022-12-02 11:00 UTC by mutec

This prevents issues in case one would return `null` or other types.

2022-12-04 19:14 UTC, SoftCreatR approved these changes

2022-12-05 08:57 UTC, TimWolla commented
Can you please further split this into 2 commits each:

1. Apply the return type to the *implementing* classes, this is valid, because return types are covariant.
2. Apply the return type to the interface itself.

2022-12-06 09:03 UTC, TimWolla requested changes
Thank you. Can you drop the annotated PHPDoc line and slightly reword the commit messages when you are rebasing anyway? “Return Value Type” misleadingly parses as “Return (Value Type)” instead of “(Value Value) Type” for me.

Let me suggest the following prasing:

- Add proper `string` return type to implementations of `Foo::bar()`
- Add proper `string` return type to `Foo::bar()`

2023-01-30 09:41 UTC, TimWolla commented on wcfsetup/install/files/lib/data/article/Article.class.php
>       * @return      string
@mutec Friendly ping.

2023-01-30 21:20 UTC, mutec commented on wcfsetup/install/files/lib/data/article/Article.class.php
>       * @return      string
I'm trying to do this tomorrow. :)

2023-02-01 08:51 UTC, TimWolla approved these changes
Perfect, thank you. I'll handle updating the return types in the other packages (including the open sourced ones).

2023-02-01 08:52 UTC, merged