Multilingual and dynamic colors in manifest.json
WoltLab/WCF pull request #5867
Opened 2024-04-03 13:27 UTC by Cyperghost

Closes #4449

2024-04-05 12:45 UTC, dtdesign requested changes

2024-04-05 12:45 UTC, dtdesign commented on wcfsetup/install/files/lib/data/style/StyleAction.class.php
> +                foreach (\glob($style->getAssetPath() . "manifest*.json") as $filename) {
```suggestion
                foreach (\glob($style->getAssetPath() . "manifest-*.json") as $filename) {
```

Wildcard patterns always have the risk of matching unrelated files and the dash is part of the expected file name.

2024-04-05 12:45 UTC, dtdesign commented on wcfsetup/install/files/lib/system/style/command/CreateManifest.class.php
> +        $this->styleID = $style->styleID;
There is no need to fetch the style again, just store the passed in Style object.

2024-04-05 12:45 UTC, dtdesign commented on wcfsetup/install/files/lib/system/style/command/CreateManifest.class.php
> +        foreach ($style->hasFavicon ? [192, 256, 512] : [192, 256] as $iconSize) {
I don’t like this, we should provide a proper 512 px version.

2024-04-05 12:45 UTC, dtdesign commented on wcfsetup/install/files/lib/system/style/command/CreateManifest.class.php
> +MANIFEST;
You should properly indent this. PHP will trim to the left based on the position of `MANIFEST;`. Thus if there are 12 spaces (or whatever) in front of it, the same amount is trimmed from all other lines too.

2024-04-05 12:45 UTC, dtdesign commented on wcfsetup/install/files/lib/data/style/Style.class.php
> +            'manifest-' . WCF::getLanguage()->languageID . '.json';
Please use `\sprintf()` instead.

2024-04-07 12:02 UTC, Fighter456 requested changes
Small typo.

2024-04-08 11:17 UTC, merged