No longer use `Database::prepareStatement()`
WoltLab/WCF pull request #6033
Opened 2024-10-22 09:33 UTC by Cyperghost

See #6002

2024-10-22 15:06 UTC, dtdesign requested changes

2024-10-22 15:06 UTC, dtdesign commented on wcfsetup/install/files/acp/update_com.woltlab.wcf_6.1_spider_step1.php
> -if (!\in_array('wcf' . WCF_N . '_spider', $tableNames)) {
This is an incorrect substitution, because this is using a fixed comparison.

2024-10-22 15:06 UTC, dtdesign commented on wcfsetup/install/files/lib/data/DatabaseObject.class.php
> +            return $classParts[0] . '1_' . static::$databaseTableName;
This is an incorrect substitution because this is meant to provide the actual table name.

2024-10-22 15:06 UTC, dtdesign commented on wcfsetup/install/files/lib/data/DatabaseObject.class.php
> +            $databaseTableNames[$className] = $classParts[0] . '1_' . \strtolower(
This is an incorrect substitution because this is meant to provide the actual table name.

2024-10-22 15:06 UTC, dtdesign commented on wcfsetup/install/files/lib/data/user/profile/visitor/UserProfileVisitorAction.class.php
> +
This looks like an incorrect change.

2024-10-22 15:06 UTC, dtdesign commented on wcfsetup/install/files/lib/system/package/plugin/ObjectTypePackageInstallationPlugin.class.php
> +                'wcf1_user'
Please verify that this (and the change in line 1127) does not cause any issues.

2024-10-22 15:06 UTC, dtdesign commented on wcfsetup/install/files/lib/system/database/editor/MySQLDatabaseEditor.class.php
> +        $statement = $this->dbObj->prepare($sql);
This and all following changes might break https://www.woltlab.com/pluginstore/file/2784-admin-tools-datenbank-und-ftp/ although I did not verify how it actually works.

2024-10-22 20:12 UTC, Cyperghost commented on wcfsetup/install/files/lib/system/database/editor/MySQLDatabaseEditor.class.php
> +        $statement = $this->dbObj->prepare($sql);
This plugin does not use any functions of `MySQLDatabaseEditor`, just requests them manually via query
```PHP
…
$sql = "SELECT table_name FROM information_schema.tables …";
$statement = WCF::getDB()->prepareStatement($sql);
…
```
Therefore, this change should not break this plugin.

2024-10-23 06:36 UTC, Cyperghost commented on wcfsetup/install/files/lib/system/package/plugin/ObjectTypePackageInstallationPlugin.class.php
> +                'wcf1_user'
These changes work, because the correct table is taken by the adjustment to `MySQLDatabaseEditor::getColumns()`.

2024-10-24 08:41 UTC, dtdesign approved these changes

2024-10-24 09:28 UTC, merged