New image viewer
WoltLab/WCF pull request #6035
Opened 2024-10-23 08:26 UTC by Cyperghost

Closes #5966

### TODO
- [ ] Remove language variables `wcf.imageViewer.*`
- [ ] Check that `.jsImageViewer` is no longer used
  - [ ] Check that `data-caption` and not `title` is used
- [ ] Use `shared_imageViewer` instead of `imageViewer`
- [ ] Rebuild `WCF.Combined.min.js` and `WCF.Combined.tiny.min.js`
- [ ] Add documentation how to use the new image viewer
  - [ ] Add migration guide from old image viewer

2024-10-23 09:55 UTC, cadeyrn commented on ts/WoltLabSuite/Core/Component/Image/Viewer.ts
> +const LOCALS = ["cs", "de", "en", "es", "fr", "it", "ja", "lv", "pl", "sk"];
typo (also in other lines): the correct spelling is locale / locales, not local / locals

2024-10-23 20:37 UTC, TimWolla reviewed
The new library should be added to https://github.com/WoltLab/WCF/blob/35e87773513755312e64cfc853f8f9d1fe3e9151/.github/workflows/javascript.yml#L39

2024-10-25 15:40 UTC, dtdesign commented
Note: This is blocked while we’re discussing the licensing terms with the vendor.

2024-11-11 14:11 UTC, dtdesign requested changes
You forgot to update `files/js/.buildOrder`, it still includes `WCF.ImageViewer`.

Also, are we somehow able to dynamically group images that exist in the same message? Currently the image viewer spans all images on one page which also means that, for example, attachments from multiple posts are mixed together.

2024-11-11 14:11 UTC, dtdesign commented on com.woltlab.wcf/templates/shared_imageViewer.tpl
> +		  document.querySelector("link[rel=\"stylesheet\"]").before(stylesheet);
```suggestion
		  document.querySelector('link[rel="stylesheet"]').before(stylesheet);
```

2024-11-11 14:11 UTC, dtdesign commented on com.woltlab.wcf/templates/shared_bbcode_wsm.tpl
> +				<a href="{$mediaLink}" data-caption="{$media->title}" class="embeddedAttachmentLink" data-fancybox="attachments">
Why is this `data-fancybox="attachments"`? The BBCode can appear in other places that have nothing to do with attachments.

2024-11-11 14:11 UTC, dtdesign commented on ts/WoltLabSuite/Core/Component/Attachment/Entry.ts
> +      link.dataset.fancybox = "attachments";
Please use a different group so that these don’t mix with other images on the page.

2024-11-11 14:11 UTC, dtdesign commented on ts/WoltLabSuite/Core/Bootstrap.ts
> +  });
We should support the legacy `.jsImageViewer` class for backwards compatibility while printing deprecation notices in the console.

2024-11-13 15:55 UTC, dtdesign reviewed
Looks good so far.

**Please do not merge it yet**, I will have to make some adjustments and conduct some further tests first.

2024-11-25 14:08 UTC, dtdesign commented
@Cyperghost This PR is now good to go.

2024-11-26 10:05 UTC, merged